# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magicTool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 573)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("background1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(7)
        MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{border-image:url(./background1.jpg)}\n"
"QTextBrowser,QFrame,QLabel,QPushButton{border-image:url()}\n"
"QTextBrowser,QTextEdit,QPushButton{background:rgba(229, 255, 239,0.5)}\n"
"QLabel{background:rgba(229, 255, 239,0)}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label_trainingResult = QtWidgets.QLabel(self.centralwidget)
        self.label_trainingResult.setGeometry(QtCore.QRect(450, 30, 71, 16))
        self.label_trainingResult.setText("")
        self.label_trainingResult.setObjectName("label_trainingResult")
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setGeometry(QtCore.QRect(450, 70, 221, 31))
        self.label_Result.setText("")
        self.label_Result.setObjectName("label_Result")
        self.labelDataNum = QtWidgets.QLabel(self.centralwidget)
        self.labelDataNum.setGeometry(QtCore.QRect(60, 90, 101, 20))
        self.labelDataNum.setObjectName("labelDataNum")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(160, 89, 81, 21))
        self.textEdit.setObjectName("textEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 140, 281, 241))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.textXExpress = QtWidgets.QTextEdit(self.frame)
        self.textXExpress.setGeometry(QtCore.QRect(80, 28, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.textXExpress.setFont(font)
        self.textXExpress.setObjectName("textXExpress")
        self.labelX = QtWidgets.QLabel(self.frame)
        self.labelX.setGeometry(QtCore.QRect(30, 30, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelX.setFont(font)
        self.labelX.setText(" x =")
        self.labelX.setTextFormat(QtCore.Qt.PlainText)
        self.labelX.setObjectName("labelX")
        self.textYExpress = QtWidgets.QTextEdit(self.frame)
        self.textYExpress.setGeometry(QtCore.QRect(80, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.textYExpress.setFont(font)
        self.textYExpress.setObjectName("textYExpress")
        self.labelY = QtWidgets.QLabel(self.frame)
        self.labelY.setGeometry(QtCore.QRect(30, 89, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelY.setFont(font)
        self.labelY.setText(" y =")
        self.labelY.setTextFormat(QtCore.Qt.PlainText)
        self.labelY.setObjectName("labelY")
        self.textZExpress = QtWidgets.QTextEdit(self.frame)
        self.textZExpress.setGeometry(QtCore.QRect(80, 141, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.textZExpress.setFont(font)
        self.textZExpress.setObjectName("textZExpress")
        self.labelZ = QtWidgets.QLabel(self.frame)
        self.labelZ.setGeometry(QtCore.QRect(30, 140, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelZ.setFont(font)
        self.labelZ.setText(" z =")
        self.labelZ.setTextFormat(QtCore.Qt.PlainText)
        self.labelZ.setObjectName("labelZ")
        self.textWExpress = QtWidgets.QTextEdit(self.frame)
        self.textWExpress.setGeometry(QtCore.QRect(80, 191, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.textWExpress.setFont(font)
        self.textWExpress.setObjectName("textWExpress")
        self.labelW = QtWidgets.QLabel(self.frame)
        self.labelW.setGeometry(QtCore.QRect(30, 190, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelW.setFont(font)
        self.labelW.setText(" w =")
        self.labelW.setTextFormat(QtCore.Qt.PlainText)
        self.labelW.setObjectName("labelW")
        self.labelFileName = QtWidgets.QLabel(self.centralwidget)
        self.labelFileName.setGeometry(QtCore.QRect(20, 400, 141, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFileName.sizePolicy().hasHeightForWidth())
        self.labelFileName.setSizePolicy(sizePolicy)
        self.labelFileName.setObjectName("labelFileName")
        self.textTrainFileName = QtWidgets.QTextEdit(self.centralwidget)
        self.textTrainFileName.setGeometry(QtCore.QRect(160, 390, 141, 31))
        self.textTrainFileName.setObjectName("textTrainFileName")
        self.textTestFileName = QtWidgets.QTextEdit(self.centralwidget)
        self.textTestFileName.setGeometry(QtCore.QRect(160, 440, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textTestFileName.sizePolicy().hasHeightForWidth())
        self.textTestFileName.setSizePolicy(sizePolicy)
        self.textTestFileName.setObjectName("textTestFileName")
        self.labelFileName_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelFileName_2.setGeometry(QtCore.QRect(20, 449, 131, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFileName_2.sizePolicy().hasHeightForWidth())
        self.labelFileName_2.setSizePolicy(sizePolicy)
        self.labelFileName_2.setObjectName("labelFileName_2")
        self.pushBtnCreat = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtnCreat.setGeometry(QtCore.QRect(130, 500, 75, 23))
        self.pushBtnCreat.setObjectName("pushBtnCreat")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(340, 140, 321, 241))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.calButton = QtWidgets.QPushButton(self.frame_2)
        self.calButton.setGeometry(QtCore.QRect(100, 60, 131, 23))
        self.calButton.setObjectName("calButton")
        self.labelTrain = QtWidgets.QLabel(self.frame_2)
        self.labelTrain.setGeometry(QtCore.QRect(90, 120, 71, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTrain.sizePolicy().hasHeightForWidth())
        self.labelTrain.setSizePolicy(sizePolicy)
        self.labelTrain.setObjectName("labelTrain")
        self.labelRateOfProgress = QtWidgets.QLabel(self.frame_2)
        self.labelRateOfProgress.setGeometry(QtCore.QRect(160, 117, 121, 21))
        self.labelRateOfProgress.setText("")
        self.labelRateOfProgress.setObjectName("labelRateOfProgress")
        self.labelResult = QtWidgets.QLabel(self.frame_2)
        self.labelResult.setGeometry(QtCore.QRect(10, 159, 301, 21))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setToolTip("")
        self.statusBar.setStatusTip("")
        self.statusBar.setAccessibleName("")
        self.statusBar.setAccessibleDescription("")
        self.statusBar.setStyleSheet("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 696, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.calButton.clicked.connect(MainWindow.magicCalc)
        self.pushBtnCreat.clicked.connect(MainWindow.create)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据预测小工具-alpha"))
        self.labelDataNum.setText(_translate("MainWindow", "设置样本数量："))
        self.textEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">样本数量确定了x的初始值域范围，比如样本数量为100，则x的值域为[1,100]的100个数</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">100</p></body></html>"))
        self.frame.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">x,y,z只能小写</span></p></body></html>"))
        self.textXExpress.setToolTip(_translate("MainWindow", "<html><head/><body><p>请输入只含x的表达式，对初始x进行变换，如果等于\'x\',则x会随机排序</p></body></html>"))
        self.textXExpress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">x</p></body></html>"))
        self.textYExpress.setToolTip(_translate("MainWindow", "<html><head/><body><p>请输入只包含x的表达式，如果输入的是\'x\',则y的值域与x相同，但是会对y随机排序</p></body></html>"))
        self.textYExpress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">x</p></body></html>"))
        self.textZExpress.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">请输入只包含x和y的表达式</span></p></body></html>"))
        self.textWExpress.setToolTip(_translate("MainWindow", "<html><head/><body><p>请输入只包含x、y、z的表达式</p></body></html>"))
        self.labelFileName.setText(_translate("MainWindow", "保存训练数据文件名："))
        self.textTrainFileName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\">train.csv</span></p></body></html>"))
        self.textTestFileName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'新宋体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\">test.csv</span></p></body></html>"))
        self.labelFileName_2.setText(_translate("MainWindow", "保存测试数据文件名："))
        self.pushBtnCreat.setText(_translate("MainWindow", "开始生成"))
        self.calButton.setText(_translate("MainWindow", "开始训练并预测"))
        self.labelTrain.setText(_translate("MainWindow", "训练进度："))

